export const LENGTH = 40;

export const RIDERS = [
  { name: "anna gasser", fileName: "anna_gasser.png" },
  { name: "austen sweetin", fileName: "austen_sweetin.png" },
  { name: "ben ferguson", fileName: "ben_ferguson.png" },
  { name: "blake paul", fileName: "blake_paul.png" },
  { name: "bode merrill", fileName: "bode_merrill.png" },
  { name: "chris rasman", fileName: "chris_rasman.png" },
  { name: "elena hight", fileName: "elena_hight.png" },
  { name: "elias elhardt", fileName: "elhardt_elias.png" },
  { name: "eric jackson", fileName: "eric_jackson.png" },
  { name: "gigi rüf", fileName: "gigi_ruf.png" },
  { name: "hailey langland", fileName: "hailey_langlands.png" },
  { name: "hana beaman", fileName: "hana_beaman.png" },
  { name: "jamie anderson", fileName: "jamie_anderson.png" },
  { name: "marion haerty", fileName: "marion_haerty.png" },
  { name: "mark m¢morris", fileName: "mark_mcmorris.png" },
  { name: "mikkel bang", fileName: "mikkel_bang.png" },
  { name: "nils mindnich", fileName: "nils_mindnich.png" },
  { name: "pat moore", fileName: "pat_moore.png" },
  { name: "robin vangyn", fileName: "robin_vangyn.png" },
  { name: "sage kotsenburg", fileName: "sage_kotsenburg.png" },
  { name: "travis rice", fileName: "travis_rice.png" },
  { name: "werni stock", fileName: "verni_stock.png" },
  { name: "victor delerue", fileName: "victor_delerue.png" },
  { name: "zoi sadowski-synnott", fileName: "zoi_sadowski-synnott.png" },
];
